parameters:
    ezsettings.default.maintenance_mode.enabled: false
    ezsettings.default.maintenance_mode.allowed_ips: []
    ezsettings.default.maintenance_mode.response_code: 503
    ezsettings.default.maintenance_mode.template: ~
