services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

    EzSystems\EzPlatformMaintenanceModeBundle\EventListener\MaintenanceModeListener:
        tags:
            # priority 44 to execute right after \eZ\Publish\Core\MVC\Symfony\EventListener\SiteAccessMatchListener
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 44 }